stages:
  - pre-check
  - prepare
  - build
  - publish

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  SUPERVISOR_IMAGE: $CI_REGISTRY_IMAGE:supervisord-$CI_COMMIT_REF_SLUG
  APP_TIMEZONE: ${APP_TIMEZONE}

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"

composer_install:
  stage: prepare
  script:
    - composer install --ignore-platform-reqs --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: "1 days"
  cache:
    paths:
      - vendor/
  tags:
    - php-composer
  only:
    - develop
    - uat
    - release

build_staging:
  stage: build
  before_script:
    - chmod +x setup_dev_env.sh
    - ./setup_dev_env.sh
    - docker build -t $APP_IMAGE .
    - docker build -t $SUPERVISOR_IMAGE --file supervisord.Dockerfile .
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker push $APP_IMAGE
    - docker push $SUPERVISOR_IMAGE
  after_script:
    - "docker image rm -f $APP_IMAGE || true"
    - "docker image rm -f $SUPERVISOR_IMAGE || true"

  tags:
    - php-shell
  only:
    - develop

build_prod:
  stage: build
  before_script:
    - chmod +x setup_prod_env.sh
    - ./setup_prod_env.sh
    - docker build -t $APP_IMAGE .
    - docker build -t $SUPERVISOR_IMAGE --file supervisord.Dockerfile .
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker push $APP_IMAGE
    - docker push $SUPERVISOR_IMAGE
  after_script:
    - docker image rm -f $APP_IMAGE || true
    - docker image rm -f $SUPERVISOR_IMAGE || true
  tags:
    - php-shell
  only:
    - release

publish_staging:
  stage: publish
  script:
    - curl -f -X POST "$STAGE_SUPERVISOR_WEBHOOK"
  tags:
    - php-shell
  only:
    - develop

publish_prod:
  stage: publish
  script:
    - curl -f -X POST "$PROD_SUPERVISOR_WEBHOOK"
  tags:
    - php-shell
  only:
    refs:
      - release
  environment:
    name: production
