cat >> .env << EOF
APP_NAME="$APP_NAME"
APP_ENV=develop
APP_KEY="$APP_KEY"
APP_TIMEZONE="$APP_TIMEZONE"
LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
RABBITMQ_HOST="$STAGE_RABBITMQ_HOST"
RABBITMQ_PORT="$STAGE_RABBITMQ_PORT"
RABBITMQ_USER="$STAGE_RABBITMQ_USER"
RABBITMQ_PASSWORD="$STAGE_RABBITMQ_PASSWORD"
RABBITMQ_VHOST="$STAGE_RABBITMQ_VHOST"
QUEUE_CONNECTION="$QUEUE_CONNECTION"
EOF
