cat >> .env << EOF
APP_NAME="$APP_NAME"
APP_ENV=release
APP_KEY="$APP_KEY"
APP_TIMEZONE="$APP_TIMEZONE"
LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
#ENCRYPTION KEY
CMAG_APP_KEY="$CMAG_APP_KEY"
# RABBITMQ CONNECTION
QUEUE_CONNECTION="$QUEUE_CONNECTION"
RABBITMQ_HOST="$STAGE_RABBITMQ_HOST"
RABBITMQ_PORT="$STAGE_RABBITMQ_PORT"
RABBITMQ_USER="$STAGE_RABBITMQ_USER"
RABBITMQ_PASSWORD="$STAGE_RABBITMQ_PASSWORD"
RABBITMQ_VHOST="$STAGE_RABBITMQ_VHOST"
# RABBITMQ_HOST="$PROD_RABBITMQ_HOST"
# RABBITMQ_PORT="$PROD_RABBITMQ_PORT"
# RABBITMQ_USER="$PROD_RABBITMQ_USER"
# RABBITMQ_PASSWORD="$PROD_RABBITMQ_PASSWORD"
# RABBITMQ_VHOST="$PROD_RABBITMQ_VHOST"
## REDIS CONNECTION
REDIS_HOST="$PROD_REDIS_HOST"
REDIS_PORT="$PROD_REDIS_PORT"
REDIS_CLIENT="$PROD_REDIS_CLIENT"
#REDIS_PASSWORD="$PROD_REDIS_PASSWORD"
REDIS_PREFIX="$PROD_REDIS_PREFIX"
# EBILL DB_CONNECTION
DB_EBILL_HOST="$DB_EBILL_HOST"
DB_EBILL_SERVICE_NAME="$DB_EBILL_SERVICE_NAME"
DB_EBILL_DATABASE="$DB_EBILL_DATABASE"
DB_EBILL_USERNAME="$DB_EBILL_USERNAME"
DB_EBILL_PASSWORD="$DB_EBILL_PASSWORD"
# POSTGRES-DB CONNECTION
DB_CONNECTION="$STAGE_DB_CONNECTION"
DB_HOST="$STAGE_DB_HOST"
DB_PORT="$STAGE_DB_PORT"
DB_DATABASE="$STAGE_DB_DATABASE"
DB_USERNAME="$STAGE_DB_USERNAME"
DB_PASSWORD="$STAGE_DB_PASSWORD"
# DB_CONNECTION="$PROD_DB_CONNECTION"
# DB_HOST="$PROD_DB_HOST"
# DB_PORT="$PROD_DB_PORT"
# DB_DATABASE="$PROD_DB_DATABASE"
# DB_USERNAME="$PROD_DB_USERNAME"
# DB_PASSWORD="$PROD_DB_PASSWORD"
EOF
