; supervisor config file
[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
user=www

[program:AccountPaymentQueue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan rabbitmq:consumer customersvc.prod.expirydate_update.customer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stopwaitsecs=60

[program:CustomerInfoModificationQueue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan rabbitmq:consumer customersvc.prod.update.customerinfo
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stopwaitsecs=60

[program:OnUserCreateQueue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan rabbitmq:consumer customersvc.prod.create.customer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stopwaitsecs=60

[program:PlanMigrationQueue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan rabbitmq:consumer customersvc.prod.planshift
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stopwaitsecs=60

# [program:run-schedule-commands]
# process_name=%(program_name)s_%(process_num)02d
# command=php /var/www/html/artisan schedule:work
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr
# stdout_logfile_maxbytes=0
# stderr_logfile_maxbytes=0
# stopwaitsecs=3600
